systemd:
  units:
    - name: datacrypt.service
      enabled: true
      contents: |
        [Unit]
        Description=Encryption at rest
        Before=systemd-user-sessions.service
        After=network-online.target
        [Service]
        Type=exec
        Environment=CRYPT_KEY_URL='<<<YOUR_KEY_URL_HERE>>>' CRYPT_CONTAINER_SIZE_PERCENTAGE='<<<YOUR_PERCENTAGE_HERE>>>'
        ExecStart=/usr/local/bin/encryption-start.sh
        ExecStop=/usr/local/bin/encryption-stop.sh
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /usr/local/bin/encryption-start.sh
      mode: 0755
      contents:
        source: https://raw.githubusercontent.com/300481/datacrypt/fcos-0.2.0/files/startscripts/encryption.sh
    - path: /usr/local/bin/encryption-stop.sh
      mode: 0755
      contents:
        source: https://raw.githubusercontent.com/300481/datacrypt/fcos-0.2.0/files/stopscripts/shutdown.sh